### ISSUE TITLE
Definir horários dos dailys

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil#5]
Definir um horário para o grupo compartilhar informações do andamento do proj.
Responder: 
O que você fez ontem?
O que você fará hoje?
Há algum impedimento no seu caminho?

**Comment by RochaCarla** [comment]
Até hoje essa issue não foi fechada? por que?

**Comment by Matheus-AM** [comment]
Esquecemos de fechá-la. Foi definida no dia que fizemos o treinamento de scrum. (19:00 até 19:15)
